### ISSUE TITLE
Seems element name isn't always set.

### ISSUE THREAD

**Issue by ekes** [localgovdrupal/localgov_search#1]
https://github.com/localgovdrupal/localgov_search/blob/1a6beb04df91b0a3e76ee20bcc1b01e1496fbc1c/localgov_search.module#L68

In the entity browser view (example on test at the moment: go to add a location to a venue; also probably if you enable content with the paragraphs browser) there doesn't seem to be an element #name

```
Notice: Undefined index: #name in localgov_search_views_pre_render() (line 68 of modules/contrib/localgov_search/localgov_search.module).
```

**Comment by stephen-cox** [comment]
Fixed with https://github.com/localgovdrupal/localgov_search/commit/4bd95f203f9aa8fcb432b053d14716be94a27e8c
