### ISSUE TITLE
Add Best bets or Search Overrides to core

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_search#33]
Waltham Forest demonstrated using https://www.drupal.org/project/search_api_best_bets 

This looked really cool! Can we bring it into our default install? 

@andybroomfield also mentioned the https://www.drupal.org/project/search_overrides might be better

@andybroomfield could you expand on the pros and cons from your experience?

**Comment by andybroomfield** [comment]
Not had too much time to check however, these essentially provide promoition / exclusion rules for search results.
Overrides was preffered as it allows users to determine the order in which pages where promoted.

That said, unless our config actully included anything that relied on this, we could leave this option open or make suggestions as I don't think its something we need to define straight away.

**Comment by willguv** [comment]
Hi @andybroomfield could you post pros and cons about Search Overrides please? Many thanks!

**Comment by willguv** [comment]
Ryan: would be useful

Jamie: no time to maintain this

Andy: Search overrides allows multiple pages to be promoted, and some pages to be demoted/ excluded

Stephen: Looks like we need Solr to run this, bigger step

Keelan: pins results using different tech, needs time to do this. Is this an indication that search isn't performing well enough? Also far more people come in through Google

**Comment by andybroomfield** [comment]
We should try both of these maybe on demo site but I don't think you can install both at the same time.
And then try and compare. I think one is just using elevate to promote results, and the other allows multiple overrides and exclusion rules to be defined which are more flexible. Also we have to consider who will be editing these overrides and where (dev or content editor task).

**Comment by willguv** [comment]
Not doing at this time so closing
