### ISSUE TITLE
Search results template / styling

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_search#39]
We currently have no consistent display for search results in LocalGov Drupal

https://demo.localgovdrupal.org/search?s=council

We need to 
- [x] Confirm the display modes (search results)
- [x] Review all modules that deploy content types and add an issue to each to make the saerch result nice!

Work from Waltham Forest might be useful, at least for LocalGov Services. 

See https://www.walthamforest.gov.uk/search?search=birth

**Comment by finnlewis** [comment]
@markconroy @msayoung @richard-s-rowley @willguv 

Any thoughts on how to define consistent display modes for search results?

**Comment by markconroy** [comment]
I'm a big fan of single templates for single view modes that can then be used across all content types. So ... my preference - same as teaser, card, etc - would be to have a template in `localgov_base` called `node--search-result.html.twig` and we put the layout in there. Then all content types will have the same layout.

If a content type in a module has a more specific template - like `node--event--search-result.html.twig` we can easily create the same template in our theme and set it to `{% include <our-theme-template>html.twig %} (like we are doing with `node--news--teaser.html.twig`

P.S. Those Waltham Forest search results look _really_ nice.

**Comment by ekes** [comment]
Worth noting the WF live version are fields output not entity output; but the module they supplied does suggest method for the same using entity output. The bigger part there being making the view modes for search results with the custom output (eg. Services landing pages highlighting particular listed pages).

**Comment by finnlewis** [comment]
I've created an issue in each project that provides a content type, so we can address each there and perhaps get help from others,

- https://github.com/localgovdrupal/localgov_services/issues/172
- https://github.com/localgovdrupal/localgov_guides/issues/93
- https://github.com/localgovdrupal/localgov_step_by_step/issues/61
- https://github.com/localgovdrupal/localgov_directories/issues/215
- https://github.com/localgovdrupal/localgov_events/issues/83
- https://github.com/localgovdrupal/localgov_news/issues/70
- https://github.com/localgovdrupal/localgov_subsites/issues/97

**Comment by markconroy** [comment]
We've currently got this template - https://github.com/localgovdrupal/localgov_base/blob/1.x/templates/content/node--search-result.html.twig - for `node--search-result.html.twig`, but it's just a very basic node template.

It would be worth laying it out something like our teaser template - image left, title/content on right or similar.
